// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClt45czDDxFReskNGJVZgH8tKnk4x1hGU',
    appId: '1:629374025046:web:30b94dd6643f5a186aaaf7',
    messagingSenderId: '629374025046',
    projectId: 'flashcard-f6ade',
    authDomain: 'flashcard-f6ade.firebaseapp.com',
    storageBucket: 'flashcard-f6ade.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjj7RwPDdDzbOkuDbeedwB4zoTWg7kjaQ',
    appId: '1:629374025046:android:2d1d59b15a704c956aaaf7',
    messagingSenderId: '629374025046',
    projectId: 'flashcard-f6ade',
    storageBucket: 'flashcard-f6ade.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3FBNaFM4K6HrIRCb7hiCUICgMaSnOd9s',
    appId: '1:629374025046:ios:1798a27d981770c16aaaf7',
    messagingSenderId: '629374025046',
    projectId: 'flashcard-f6ade',
    storageBucket: 'flashcard-f6ade.appspot.com',
    iosBundleId: 'com.example.flashcardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3FBNaFM4K6HrIRCb7hiCUICgMaSnOd9s',
    appId: '1:629374025046:ios:1798a27d981770c16aaaf7',
    messagingSenderId: '629374025046',
    projectId: 'flashcard-f6ade',
    storageBucket: 'flashcard-f6ade.appspot.com',
    iosBundleId: 'com.example.flashcardApp',
  );
}
